# Как часто перезапрашивать списки ИТМО (секунды).
cache_ttl_seconds: 45

programs:
  - name: "Веб-технологии"
    short: "Веб"
    code: "09.04.04"
    url: "https://abit.itmo.ru/rating/master/budget/2379"
  - name: "Веб-технологии"
    short: "Веб"
    code: "09.04.04"
    url: "https://abit.itmo.ru/rating/master/contract/2379"
  - name: "Системное и прикладное ПО"
    short: "СППО"
    code: "09.04.04"
    url: "https://abit.itmo.ru/rating/master/budget/2444"
  - name: "Системное и прикладное ПО"
    short: "СППО"
    code: "09.04.04"
    url: "https://abit.itmo.ru/rating/master/contract/2444"
  - name: "Нейротехнологии и программная инженерия"
    short: "Нейро"
    code: "09.04.04"
    url: "https://abit.itmo.ru/rating/master/budget/2382"
  - name: "Нейротехнологии и программная инженерия"
    short: "Нейро"
    code: "09.04.04"
    url: "https://abit.itmo.ru/rating/master/contract/2382"
  - name: "Технологии разработки компьютерных игр"
    short: "Игры"
    code: "09.04.03"
    url: "https://abit.itmo.ru/rating/master/budget/2377"
  - name: "Технологии разработки компьютерных игр"
    short: "Игры"
    code: "09.04.03"
    url: "https://abit.itmo.ru/rating/master/contract/2377"
  - name: "Искусственный интеллект"
    short: "ИИ"
    code: "11.04.02"
    url: "https://abit.itmo.ru/rating/master/budget/2390"
  - name: "Искусственный интеллект"
    short: "ИИ"
    code: "11.04.02"
    url: "https://abit.itmo.ru/rating/master/contract/2390"
  - name: "Программное обеспечение высоконагруженных систем"
    short: "Высоконагр."
    code: "01.04.02"
    url: "https://abit.itmo.ru/rating/master/budget/2362"
  - name: "Программное обеспечение высоконагруженных систем"
    short: "Высоконагр."
    code: "01.04.02"
    url: "https://abit.itmo.ru/rating/master/contract/2362"
  - name: "Мобильные и облачные технологии"
    short: "Мобильные"
    code: "09.04.03"
    url: "https://abit.itmo.ru/rating/master/budget/2376"
  - name: "Мобильные и облачные технологии"
    short: "Мобильные"
    code: "09.04.03"
    url: "https://abit.itmo.ru/rating/master/contract/2376"
  - name: "Фронтенд и бэкенд разработка"
    short: "Фронт/бэк"
    code: "09.04.03"
    url: "https://abit.itmo.ru/rating/master/budget/2378"
  - name: "Фронтенд и бэкенд разработка"
    short: "Фронт/бэк"
    code: "09.04.03"
    url: "https://abit.itmo.ru/rating/master/contract/2378"
